[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

upload_protocol = espota
upload_port = 10.54.116.117
upload_flags =
    --auth=esp32ota

monitor_port = socket://10.54.116.117:23
monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11
    adafruit/Adafruit BusIO @ ^1.16.1
    teemuatlut/TMCStepper @ ^0.7.3
    waspinator/AccelStepper @ ^1.64
    plerup/EspSoftwareSerial @ ^8.1.0